name: Backend CD (production)

on:
  workflow_run:
    workflows:
      - "Backend CI"
    types:
      - completed
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn build:all
      - name: Run database migrations
        env:
          MIGRATE_dbConnectionUri: ${{ secrets.MONGO_MIGRATE_URL_PRODUCTION }}
          MONGO_URL: ${{ secrets.MONGO_URL_PRODUCTION }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME_PRODUCTION }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD_PRODUCTION }}
        run: yarn migrate up --autosync
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x 'resources*' -x 'node_modules*' -x 'src*'
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_PRODUCTION_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_PRODUCTION_SECRET_KEY }}
          application_name: ugram-backend
          environment_name: ugram-backend-production-2
          version_label: "ugram-backend-production-2-${{ steps.format-time.outputs.replaced }}"
          region: ca-central-1
          deployment_package: backend/deploy.zip
