name: Frontend CD (staging)

on:
  workflow_run:
    workflows:
      - "Frontend CI"
    types:
      - completed
    branches:
      - develop

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_KEY }}
          aws-region: ca-central-1
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Build static site
        run: yarn build:staging
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://staging.ugram.ca --delete
